# Generated by Django 4.1.4 on 2022-12-08 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spammer", "0002_alter_distribution_expiration_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("order",),
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="distribution",
            options={
                "ordering": ("order",),
                "verbose_name": "Рассылки",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("order",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="tag",
            field=models.CharField(blank=True, max_length=10, verbose_name="Тег"),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone_code",
            field=models.IntegerField(
                blank=True, verbose_name="Код мобильного оператора клиента"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="expiration_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 9, 14, 49, 56, 934484, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время завершения рассылки",
            ),
        ),
    ]
