# Generated by Django 4.1.4 on 2022-12-08 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spammer", "0004_alter_client_telephone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="expiration_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 9, 14, 59, 20, 10364, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата и время завершения рассылки",
            ),
        ),
    ]
